accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('profile/<username>', views.profile, name='profile'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),

    #kakao 
    path('kakao_login/', views.kakao_login, name='kakao_login'),
    path('kakao_unlink/', views.kakao_unlink, name='kakao_unlink'),
    path('auth/', views.oauth, name='auth'),
]

articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    # article
    path('', views.articles, name='articles'),
    path('create/', views.article_create, name='article_create'),
    path('<int:article_pk>/', views.article_detail, name='article_detail'),
    path('<int:article_pk>/update/', views.article_update, name='article_update'),
    path('<int:article_pk>/delete/', views.article_delete, name='article_delete'),
    path('<int:article_pk>/like/', views.article_like, name='article_like'),
    # comment
    path('<int:article_pk>/comments/create/', views.comment_create, name='comment_create'),
    path('<int:article_pk>/comments/<int:comment_pk>/update/', views.comment_update, name='comment_update'),
    path('<int:article_pk>/comments/<int:comment_pk>/delete/', views.comment_delete, name='comment_delete'),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
    path('search/', views.searching, name='search'),
]

movie_project/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', include('home.urls')),
    path('accounts/', include('accounts.urls')),
    path('articles/', include('articles.urls')),
    path('movies/', include('movies.urls')),

]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    followings = models.ManyToManyField('self', symmetrical=False)
    profile_image = models.CharField(max_length=300)
    thumbnail_image = models.CharField(max_length=300)
    birthday = models.CharField(max_length=50)
    gender = models.CharField(max_length=50)

articles/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Article(models.Model): 
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_articles')
    
    def __str__(self):
        return self.title


class Comment(models.Model):  
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.title

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model
from django import forms



class CustomUserCreationForm(UserCreationForm):
    
    profile_image = forms.CharField(max_length=150, required=False)

    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = UserCreationForm.Meta.fields + ('email','profile_image' )



class CustomUserUpdateForm(UserChangeForm):

    gender_choice = [
        ('male', 'male'),
        ('female', 'female')
    ]

    username = forms.CharField(max_length=100, required=True)
    birthday = forms.CharField(max_length=100, required=True)
    gender = forms.CharField(max_length=100, required=True, widget=forms.Select(choices = gender_choice))

    class Meta:
        model = get_user_model()
        fields = ['username', 'profile_image', 'birthday', 'gender']

accounts/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth import login as auth_login, logout as auth_logout, get_user_model, update_session_auth_hash
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods, require_POST
from .forms import CustomUserCreationForm, CustomUserUpdateForm
from django.core.paginator import Paginator
from decouple import config
import requests

def oauth(request):
    code = request.GET.get('code', None)
    client_id = request.session.get('client_id')
    redirect_uri = request.session.get('redirect_uri')

    access_token_request_uri = "https://kauth.kakao.com/oauth/token?grant_type=authorization_code&"
    access_token_request_uri += "client_id=" + client_id
    access_token_request_uri += "&redirect_uri=" + redirect_uri
    access_token_request_uri += "&code=" + code

    access_token_request_uri_data = requests.get(access_token_request_uri)
    json_data = access_token_request_uri_data.json()
    access_token = json_data['access_token']

    url = 'https://kapi.kakao.com/v2/user/me'
    headers = {
        'Authorization': f'Bearer {access_token}',
        'Content-type': 'application/x-www-form-urlencoded; charset-utf-8',
    }
    kakao_response = requests.get(url, headers=headers).json()

    User = get_user_model()

    try:
        email = kakao_response['kakao_account']['email']
    except:
        email = 'kakao_account' + str(kakao_response['id'])

    if User.objects.filter(email = email).exists():
        user = User.objects.get(email = email)
        
        auth_login(request, user)
        return redirect('home:home')
        
    
    User(
        username = kakao_response['properties']['nickname'],
        last_name = kakao_response['id'],
        profile_image = kakao_response['properties']['profile_image'],
        thumbnail_image = kakao_response['properties']['thumbnail_image'],
        birthday = kakao_response['kakao_account']['birthday'],
        gender = kakao_response['kakao_account']['gender'],
        email = email,
    ).save()

    user = User.objects.get(email = email)
    
    auth_login(request, user)
    return redirect('home:home')


def kakao_login(request):
    login_request_uri = 'https://kauth.kakao.com/oauth/authorize?'
    client_id = config('KAKAO_LOGIN_client_id')
    redirect_uri = 'http://127.0.0.1:8000/accounts/auth'
    login_request_uri += 'client_id=' + client_id
    login_request_uri += '&redirect_uri=' + redirect_uri
    login_request_uri += '&response_type=code'

    request.session['client_id'] = client_id
    request.session['redirect_uri'] = redirect_uri

    return redirect(login_request_uri)

def kakao_unlink(request):
    unlink_request_url = 'https://kapi.kakao.com/v1/user/unlink'
    User = get_user_model()
    user = User.objects.get(email = request.user.email)
    headers = {
        'Authorization': config('ADMIN_KEY'),
    }
    params = {
        'Authorization': config('ADMIN_KEY'),
        'target_id': user.last_name,
        'target_id_type': "user_id",
    }
    unpluged = requests.post(unlink_request_url, headers=headers, params=params).json()
    auth_logout(request)
    user.delete()
    return redirect('home:home')


@require_http_methods(['GET', 'POST'])
def signup(request):
    if 'POST' == request.method:
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            'https://user-images.githubusercontent.com/89068148/170427885-7cfa46be-c5a8-48c8-bc7e-cb8ffe19ca93.png'
            user = form.save()
            auth_login(request, user)
            return redirect('articles:articles')
    else:
        form = CustomUserCreationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/signup.html', context)

@require_http_methods(['GET', 'POST'])
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('home:home')
    else:
        form = PasswordChangeForm(request.user)
    context = {
        'form':form,
    }
    return render(request, 'accounts/change_password.html', context)


@require_http_methods(['GET', 'POST'])
def login(request):
    if request.user.is_authenticated:
        return redirect('home:home')
    if 'POST' == request.method:
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect(request.GET.get('next') or 'home:home')
    else:
        form = AuthenticationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/login.html', context)


@require_POST
def logout(request):
    if request.user.is_authenticated:
        auth_logout(request)
    return redirect('home:home')


@login_required
def update(request):
    if request.method == 'POST':
        change_from = CustomUserUpdateForm(request.POST, instance=request.user)
        if change_from.is_valid():
            change_from.save()
            return redirect('accounts:profile', request.user.username)
    else:
        change_from = CustomUserUpdateForm(instance=request.user)
    context = {
        'form':change_from
    }
    return render(request, 'accounts/update.html', context)


def profile(request, username):
    person = get_object_or_404(get_user_model(), username=username)
    context = {
        'person': person,
    }
    return render(request, 'accounts/profile.html', context)

templates/accounts/change_password.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
  <h2 class="my-3 border-bottom pb-2 text-secondary fw-bold">Password Change</h2>
  <form action="" method="post" class="post-form my-3">
    {% csrf_token %}
    <!-- 오류 표시 -->
    {% with form=form %}
      {% include 'errors.html' %}
    {% endwith %}
    <!-- 오류 표시 -->
    <div class="form-group my-3">
      <label for="old_password" class="form-label text-secondary">기존 비밀번호</label>
      <input type="password" name="old_password" id="old_password" class="form-control bg-secondary text-light">
    </div>
    <div class="form-group my-3">
      <label for="new_password1" class="form-label text-secondary">새 비밀번호</label>
      <input type="password" name="new_password1" id="new_password1" class="form-control bg-secondary text-light">
    </div>
    <div class="form-group my-3">
      <label for="new_password2" class="form-label text-secondary">새 비밀번호 확인</label>
      <input type="password" name="new_password2" id="new_password2" class="form-control bg-secondary text-light">
    </div>

    <button type="submit" class="btn btn-danger fw-bold">Change</button>
    <a href="{% url 'home:home' %}" class="btn btn-secondary ms-auto fw-bold" style="width: 68.25px;">Back</a>
  </form>
</div>
{% endblock content %}
















<br><br><br><br>
<div class="bg-white">

    <form action="{% url 'accounts:change_password' %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit">
    </form>
</div>

templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
<br><br><br><br>
<div class="container">
  <h2 class="my-3 border-bottom pb-2 text-secondary fw-bold">Login</h2>
  <form action="{% url 'accounts:login' %}" method="post" class="post-form my-3">
    {% csrf_token %}
    <!-- 오류 표시 -->
    {% with form=form %}
      {% include 'errors.html' %}
    {% endwith %}
    <!-- 오류 표시 -->
    <div class="form-group my-3">
      <label for="username" class="form-label text-secondary">Username</label>
      <input type="text" name="username" id="username" class="form-control bg-secondary text-light">
    </div>
    <div class="form-group my-3">
      <label for="password" class="form-label text-secondary">Password</label>
      <input type="password" name="password" id="password" class="form-control bg-secondary text-light">
    </div>
    <button type="submit" class="btn btn-danger fw-bold">Login</button>
    <a href="{% url 'articles:articles' %}" class="btn btn-secondary ms-auto fw-bold" style="width: 68.25px;">Back</a>
  </form>
  <a href="{% url 'accounts:kakao_login' %}">
    <img src="https://user-images.githubusercontent.com/89068148/170420840-ee7595d5-f64a-4cfb-9050-b945c4015f3e.png" alt="">
  </a>
</div>
{% endblock %}

templates/accounts/profile.html
{% extends 'base.html' %}


{% block content %}
<br><br><br><br>
<div class="container-fluid px-4">
  <h1 class="text-light">Profile</h1>
  <div class="container my-5 bg-dark-secondary">
    <!-- username -->
    <div class="container border-bottom p-3">
      <h2 class="text-light mb-0">
        <strong>Welcome ! {{ person.username }} </strong>
      </h2>
      <div class="container mt-5 mb-5">
        <div class="row no-gutters">
            <div class="col-md-4 col-lg-4"><img class="bg-black" src={% if person.profile_image %}"{{ person.profile_image }}"{% else %}"https://user-images.githubusercontent.com/89068148/170430095-1ab94981-0d1d-4110-993a-6914ce7a62bf.jpg"{% endif %}></div>
            <div class="col-md-8 col-lg-8">
                <div class="d-flex flex-column">
                    <div class="d-flex flex-row justify-content-between align-items-center p-5 bg-dark text-white">
                        <h3 class="display-5"> {{ person.username }}</h3> {{ person.email }}</div>
                    <div class="p-3 bg-black text-white">
                      <h5>SSAFY _ GUMI 3  |  7 TH 소속</h5>
                      <hr>
                      <h6>sign_up : {{ person.date_joined }} / 
                        birth : {% if person.birthday %}{{ person.birthday }}{% else %}정보 없음{% endif %} /
                        gender : {% if person.gender %}{{ person.gender }}{% else %}정보 없음{% endif %}
                      </h6>
                    </div>
                    <div class="d-flex flex-row text-white">
                        <div class="p-4 bg-primary text-center skill-block">
                            <h1>
                              {% if person.article_set.count > 0 %}{{ person.article_set.count }}{% else %}0{% endif %}
                            </h1>
                            <h5>게시글</h5>
                        </div>
                        <div class="p-3 bg-success text-center skill-block">
                          <h1>
                            {% if person.comment_set.count > 0 %}{{ person.comment_set.count }}{% else %}0{% endif %}
                          </h1>
                          <h5>댓글</h5>
                        </div>
                        <div class="p-3 bg-warning text-center skill-block">
                          <h1>
                            {% if person.like_articles.count > 0 %}{{ person.like_articles.count }}{% else %}0{% endif %}
                          </h1>
                          <h5><i class="fa-solid fa-heart"></i> 게시글</h5>
                        </div>
                        <div class="p-3 bg-danger text-center skill-block">
                          <h1>
                            {% if person.like_articles.count > 0 %}{{ person.like_articles.count }}{% else %}0{% endif %}
                          </h1>
                          <h5><i class="fa-solid fa-heart"></i> 영화</h5>
                        </div>
                    </div>
                  </div>
                </div>
              </div>
              <br>
              {% if request.user.username == person.username %}
              <div class="container row m-2">
                <div class="bg-warning m-2" style="border-radius: 10px; width:150px; text-align:center; padding-top:7px; padding-bottom:1px">
                  <a href="{% url 'accounts:kakao_unlink' %}" style="text-decoration:none; color:black">
                    <h5><i class="fa-solid fa-right-from-bracket"></i> 회원탈퇴</h6>
                    </a>
                  </div>
                  <div class="bg-warning m-2" style="border-radius: 10px; width:150px; text-align:center; padding-top:7px; padding-bottom:1px">
                    <a href="{% url 'accounts:update' %}" style="text-decoration:none; color:black">
                      <h5><i class="fa-solid fa-circle-info"></i> 정보 수정</h5>
                      </a>
                  </div>
              </div>
                {% endif %}
    </div>
        
        
    </div>
  
    <!-- 작성 게시글 목록 -->
    <div class="container border-bottom p-3">
      <div class="container p-3">
        <h2 class="text-light mb-0">
          Articles
        </h2>
      </div>
      <div class="list-group rounded-0 bg-dark">
        {% for article in person.article_set.all %}
        <a href="{% url 'articles:article_detail' article.pk %}" class="list-group-item list-group-item-action bg-dark">
          <div class="d-flex w-100 justify-content-between">
            <h6 class="mb-1 text-light">
              {{ article.title }}
              {% if article.comment_set.count > 0 %}
              <span class="small text-danger fw-bold py-2">
                {{ article.comment_set.count }}
              </span>
              {% endif %}
            </h6>
            <span class="badge bg-danger rounded-pill">{{ article.like_users.count }}</span>
          </div>
          <small class="text-secondary">{{ article.created_at|date:'y-m-d H:i' }}</small>
        </a>
        {% endfor %}
      </div>
    </div>
  
    <!-- 작성 댓글 목록 -->
    <div class="container border-bottom p-3">
      <div class="container p-3">
        <h2 class="text-light mb-0">
          Comments
        </h2>
      </div>
      <div class="list-group rounded-0 bg-dark">
        {% for comment in person.comment_set.all %}
        <a href="{% url 'articles:article_detail' comment.article.pk %}" class="list-group-item list-group-item-action bg-dark">
          <div class="d-flex w-100 justify-content-between">
            <h6 class="mb-1 text-light">
              {{ comment.content }}
            </h6>
            <small class="text-secondary">{{ comment.article.title }}</small>
          </div>
          <small class="text-secondary">{{ comment.created_at|date:'y-m-d H:i' }}</small>
        </a>
        {% endfor %}
      </div>
    </div>
  
    <!-- 좋아요 게시글 목록 -->
    <div class="container p-3">
      <div class="container p-3">
        <h2 class="text-light mb-0">
          Like Articles
        </h2>
      </div>
      <div class="list-group rounded-0 bg-dark">
        {% for article in person.like_articles.all %}
        <a href="{% url 'articles:article_detail' article.pk %}" class="list-group-item list-group-item-action bg-dark">
          <div class="d-flex w-100 justify-content-between">
            <h6 class="mb-1 text-light">
              {{ article.title }}
              {% if article.comment_set.count > 0 %}
              <span class="small text-danger fw-bold py-2">
                {{ article.comment_set.count }}
              </span>
              {% endif %}
            </h6>
            <span class="badge bg-danger rounded-pill">{{ article.like_users.count }}</span>
          </div>
          <small class="text-secondary">{{ article.created_at|date:'y-m-d H:i' }}</small>
        </a>
        {% endfor %}
      </div>
    </div>
  </div>
</div>

<style>
  img {
    width: 100%;
    height: 100%;
  }
  
  .bg-black {
    background: #000;
  }
  
  .skill-block {
    width: 30%;
  }
  
  @media (min-width: 991px) and (max-width:1200px) {
    .skill-block {
      padding: 32px !important;
    }
  }
  
  @media (min-width: 1200px) {
    .skill-block {
      padding: 56px !important;
    }
  }
</style>


{% endblock %}

templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}
<br><br><br><br>
<div class="container">
  <h2 class="my-3 border-bottom pb-2 text-secondary fw-bold">Signup</h2>
  <form action="{% url 'accounts:signup' %}" method="post" class="post-form my-3">
    {% csrf_token %}
    <!-- 오류 표시 -->
    {% with form=form %}
      {% include 'errors.html' %}
    {% endwith %}
    <!-- 오류 표시 -->
    <div class="form-group my-3">
      <label for="username" class="form-label text-secondary">Username</label>
      <input type="text" name="username" id="username" class="form-control bg-secondary text-light">
    </div>
    <div class="form-group my-3">
      <label for="email" class="form-label text-secondary">Email</label>
      <input type="email" name="email" id="email" class="form-control bg-secondary text-light">
    </div>
    <div class="form-group my-3">
      <label for="password1" class="form-label text-secondary">Password 1</label>
      <input type="password" name="password1" id="password1" class="form-control bg-secondary text-light">
    </div>
    <div class="form-group my-3">
      <label for="password2" class="form-label text-secondary">Password 2</label>
      <input type="password" name="password2" id="password2" class="form-control bg-secondary text-light">
    </div>
    <button type="submit" class="btn btn-danger fw-bold">Signup</button>
    <a  class="btn btn-secondary fw-bold" style="width: 78.95px;">Back</a>
  </form>
</div>
{% endblock %}

templates/accounts/update.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
  <h2 class="my-3 border-bottom pb-2 text-secondary fw-bold">Update</h2>
  <form action="" method="post" class="post-form my-3">
    {% csrf_token %}
    <!-- 오류 표시 -->
    {% with form=form %}
      {% include 'errors.html' %}
    {% endwith %}
    <!-- 오류 표시 -->
    <div class="form-group my-3">
      <label for="username" class="form-label text-secondary">Username</label>
      <input type="text" name="username" id="username" class="form-control bg-secondary text-light" value="{{ form.username.value|default_if_none:'' }}">
    </div>
    <div class="form-group my-3">
      <label for="profile_image" class="form-label text-secondary">Profile Image</label>
      <input type="text" name="profile_image" id="profile_image" class="form-control bg-secondary text-light">
    </div>
    <div class="form-group my-3">
      <label for="birthday" class="form-label text-secondary">Birthday</label>
      <input type="text" name="birthday" id="birthday" class="form-control bg-secondary text-light">
    </div>
    <div class="form-group my-3">
      <label for="rating" class="form-label text-secondary">Gender</label>
      <select class="form-select bg-dark text-light" name="gender">
        <option value="male" selected>male</option>
        <option value="female">female</option>
      </select>
    </div>
    <button type="submit" class="btn btn-danger fw-bold">Update</button>
    <a href="{% url 'home:home' %}" class="btn btn-secondary ms-auto fw-bold" style="width: 68.25px;">Back</a>
  </form>
  <a href="{% url 'accounts:change_password' %}" class="btn btn-secondary ms-auto fw-bold">Password Change</a>
</div>
{% endblock content %}







{% comment %} <br><br><br><br>
<div class="bg-white">
    <form action="" method="POST" class="pt-5 my-5">
        {% csrf_token %}
        {{ form.as_p }}
      
        <button class="btn btn-info">수정</button>
      </form>
</div> {% endcomment %}