accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('profile/<username>', views.profile, name='profile'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),

    #kakao 
    path('kakao_login/', views.kakao_login, name='kakao_login'),
    path('kakao_unlink/', views.kakao_unlink, name='kakao_unlink'),
    path('auth/', views.oauth, name='auth'),
]

articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    # article
    path('', views.articles, name='articles'),
    path('create/', views.article_create, name='article_create'),
    path('<int:article_pk>/', views.article_detail, name='article_detail'),
    path('<int:article_pk>/update/', views.article_update, name='article_update'),
    path('<int:article_pk>/delete/', views.article_delete, name='article_delete'),
    path('<int:article_pk>/like/', views.article_like, name='article_like'),
    # comment
    path('<int:article_pk>/comments/create/', views.comment_create, name='comment_create'),
    path('<int:article_pk>/comments/<int:comment_pk>/update/', views.comment_update, name='comment_update'),
    path('<int:article_pk>/comments/<int:comment_pk>/delete/', views.comment_delete, name='comment_delete'),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
    path('search/', views.searching, name='search'),
]

movie_project/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', include('home.urls')),
    path('accounts/', include('accounts.urls')),
    path('articles/', include('articles.urls')),
    path('movies/', include('movies.urls')),

]

movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    # movie
    path('', views.movies, name='movies'),
    path('<int:movie_pk>/', views.movie_detail, name='movie_detail'),
    # review
    path('<int:movie_pk>/reviews/create', views.review_create, name='review_create'),
    path('<int:movie_pk>/reviews/<int:review_pk>/update/', views.review_update, name='review_update'),
    path('<int:movie_pk>/reviews/<int:review_pk>/delete/', views.review_delete, name='review_delete'),
    
    # 영화 추천
    path('for-you/<int:movie_pk>/', views.for_you, name='for_you'),
    path('for-you2/<int:movie_pk>/', views.for_you2, name='for_you2'),
    path('for-you3/<int:movie_pk>/', views.for_you3, name='for_you3'),
    path('for-you4/<int:movie_pk>/', views.for_you4, name='for_you4'),
]

movies/models.py
from django.db import models
from django.conf import settings

# Create your models here.

class Movie(models.Model):
    title = models.CharField(max_length=100)
    overview = models.TextField()
    poster_path = models.CharField(max_length=500)
    genres = models.CharField(max_length=500)
    popularity = models.FloatField()
    director = models.CharField(max_length=100)
    actors = models.CharField(max_length=500)
    release_date = models.DateField()
    adult = models.BooleanField()

    def __str__(self):
        return self.title



class Review(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    content = models.CharField(max_length=300)
    rating = models.IntegerField()
    created_at = models.DateField(auto_now=False, auto_now_add=True)
    updated_at = models.DateField(auto_now=True, auto_now_add=False)

    def __str__(self):
        return self.title

movies/forms.py
from django import forms
from .models import Review

class ReviewForm(forms.ModelForm):

    CHOICES= [
        (1, '★☆☆☆☆'),
        (2, '★★☆☆☆'),
        (3, '★★★☆☆'),
        (4, '★★★★☆'),
        (5, '★★★★★')
    ]

    rating = forms.IntegerField(
        label='별 점',
        widget=forms.Select(
            choices = CHOICES,
        )
    )

    content = forms.CharField(
        label='리뷰를 작성해 보세요',
        widget=forms.Textarea()
        
    )

    class Meta:
        model = Review
        fields = ('content', 'rating')

movies/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.http import require_safe, require_http_methods, require_POST
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from movies.forms import ReviewForm
from .models import Movie, Review

actors_img = []



# path('', views.movies),
@require_safe
def movies(request):
    page = request.GET.get('page', '1')
    movies = Movie.objects.order_by('-release_date')
    MOVIES_PER_PAGE = 40
    paginator = Paginator(movies, MOVIES_PER_PAGE)
    page_movies = paginator.get_page(page)
    context = {
        'movies': page_movies
    }
    return render(request, 'movies/movies.html', context)


# path('<int:movie_pk>/', views.movie_detail),
@require_safe
def movie_detail(request, movie_pk):
    global actors_img
    movie = get_object_or_404(Movie, pk=movie_pk)
    genres = movie.genres.strip('[]').replace("'",'').split(',')[:4]
    movie.overview = movie.overview
    form = ReviewForm()

    # 영상 리스트 by youtube api
    from googleapiclient.discovery import build
    DEVELOPER_KEY = "AIzaSyC1CzkerAIdAl_9mBAjF9m1uPBzOmCvhbs"
    YOUTUBE_API_SERVICE_NAME="youtube"
    YOUTUBE_API_VERSION="v3"
    youtube = build(YOUTUBE_API_SERVICE_NAME,YOUTUBE_API_VERSION,developerKey=DEVELOPER_KEY)

    search_response_data = youtube.search().list(
    q = movie.title + '영화',
    order = "relevance",
    fields = "items(id)",
    part = "snippet",
    maxResults = 6
    ).execute()['items']

    video_list = []
    for item in search_response_data:
        video = f"https://www.youtube.com/embed/{item['id']['videoId']}?rel=0&controls=0&showinfo=0"
        video_list.append({'video':video})


    import urllib.request
    import json
    client_id = "MB8drhevCnawoQjOxc5S"
    client_secret = "D9wdXNLZar"

    encText = urllib.parse.quote(movie.title+'명장면')
    url = "https://openapi.naver.com/v1/search/image?query=" + encText
    request1 = urllib.request.Request(url)
    request1.add_header("X-Naver-Client-Id",client_id)
    request1.add_header("X-Naver-Client-Secret",client_secret)
    response = urllib.request.urlopen(request1)

    response_body = response.read()
    str_data = response_body.decode('utf-8')
    json_data = json.loads(str_data)
    
    img_movies = []
    for item in json_data['items']:
        if item['thumbnail']:
            img_movies.append({ 'img': item['thumbnail'] })
   

    # 배우정보 크롤링
    img_actors = []
    for actor in movie.actors.strip('[]').split(','):
        actor = actor.strip("''")
        encText = urllib.parse.quote(actor+'얼굴')
        url = "https://openapi.naver.com/v1/search/image?query=" + encText
        request1 = urllib.request.Request(url)
        request1.add_header("X-Naver-Client-Id",client_id)
        request1.add_header("X-Naver-Client-Secret",client_secret)
        response = urllib.request.urlopen(request1)
        
        response_body = response.read()
        answer = response_body.decode('utf-8')
        answer = json.loads(answer)
        if not answer['items']:
            continue
        answer = answer["items"][0]['thumbnail'] if answer['items'] else []
        
        img_actors.append({
            'name':actor,
            'img':answer,
        })
    
    actors_img = img_actors[:]

    context = {
        'movie': movie,
        'review_form': form,
        'genres':genres,
        'video_list':video_list,
        'img_movies':img_movies,
        'img_actors':img_actors,
    }
    return render(request, 'movies/movie_detail.html', context)


# path('<int:movie_pk>/review/', views.review_create),
@require_POST
def review_create(request, movie_pk):
    if request.user.is_authenticated:
        movie = get_object_or_404(Movie, pk=movie_pk)
        form = ReviewForm(request.POST)
        if form.is_valid():
            review = form.save(commit=False)
            review.movie = movie
            review.user = request.user
            review.save()
        return redirect('movies:movie_detail', movie.pk)
    return redirect('accounts:login')


# path('<int:movie_pk>/review/<int:review_pk>/update/', views.review_update),
# @login_required
# def review_update(request, movie_pk, review_pk):
#     pass




@login_required
@require_http_methods(['GET', 'POST'])
def review_update(request, movie_pk, review_pk):
    movie = get_object_or_404(Movie, pk=movie_pk)
    review = get_object_or_404(Review, pk=review_pk)
    if request.user != review.user:
        return redirect('movies:movie_detail', movie_pk)
    if request.method == 'POST':
        form = ReviewForm(request.POST, instance=review)
        if form.is_valid():
            form.save()
            return redirect('movies:movie_detail', movie_pk)
    else:
        form = ReviewForm(instance=review)
    context = {
        'movie': movie,
        'review': review,
        'reivew_form': form,
    }
    return render(request, 'movies/review_update.html', context)







# path('<int:movie_pk>/review/<int:review_pk>/delete/', views.review_delete),
@require_POST
def review_delete(request, movie_pk, review_pk):
    if request.user.is_authenticated:
        review = get_object_or_404(Review, pk=review_pk)
        if request.user == review.user:
            review.delete()
    return redirect('movies:movie_detail', movie_pk)


def for_you(request, movie_pk):
    global actors_img
    pick_movie = get_object_or_404(Movie, pk=movie_pk)
    movies = Movie.objects.all()
    movies = [movie for movie in movies if movie.pk != movie_pk]
    
    # 배우 기반 추천
    recommend_movies_by_actors = []
    flag = 0
    for movie in movies:
        if flag:
            flag = 0
            continue
        for item in actors_img:
            actor = item['name']
            if flag:
                break
            if actor in movie.actors:
                recommend_movies_by_actors.append({'actor':actor.strip("''"), 'actor_img': [i['img'] for i in actors_img if i['name'] == actor], 'movie':movie})
                flag = 1
                break

    context = {
        'recommend_movies_by_actors' : recommend_movies_by_actors,
        'pick_movie' : pick_movie,
    }

    return render(request, 'movies/movie_for_you.html', context)
    

# 장르기반
def for_you2(request, movie_pk):
    pick_movie = get_object_or_404(Movie, pk=movie_pk)
    movies = Movie.objects.all()
    movies = [movie for movie in movies if movie.pk != movie_pk]
    # 장르 기반 추천
    flag = 0
    genres = pick_movie.genres
    recommend_movies_by_genres = []
    for movie in movies:
        if flag:
            flag = 0
            continue
        same_genre = []
        cnt = 0

        for genre in genres.strip('[]').split(','):
            if genre in movie.genres:
                same_genre.append(genre)
                cnt += 1
                
            if cnt >= 3:
                    recommend_movies_by_genres.append({'movie':movie, 'same_genres':same_genre})
                    flag = 1
                    break
    
    context = {
        'recommend_movies_by_genres' : recommend_movies_by_genres,
        'pick_movie' : pick_movie,
    }

    return render(request, 'movies/movie_for_you2.html', context)


def for_you3(request, movie_pk):
    pick_movie = get_object_or_404(Movie, pk=movie_pk)
    movies = Movie.objects.all()
    movies = [movie for movie in movies if movie.pk != movie_pk]
    # 줄거리 기반 추천
    pick_movie_keywords = pick_movie.overview.replace('.','').replace(',','').split()
    pick_movie_keywords = set([i for i in pick_movie_keywords if i not in {'그', '된다', \
        '되어', '되고', '은', '는', '이', '가', '어느', '있는', '된', '바로', '때', '알게', '통해',\
        '위해', '할', '날', '자신을', '나오는', '무렵', '전부', '수', '자신이', '그가', '마침내',\
        '전', '있음을', '알', '없는', '한', '후', '한', '두', '될', '채', '더', '그의', '그가', '그는',\
        '모든', '하지만', '최고의', '하는데', '그리고', '오랜', '못한', '예상치', '새로운', '들어온', '속', '맞서', '하는데…',\
        '맞서', '넘어', '것', '함께', '차츰', '마치고', '사이에는', '그에게' , '서로의', '가능한', '겪으며'}])
    answer = []
    for movie in movies:
        temp = set(movie.overview.split())
        same_keywords = pick_movie_keywords & temp
        if len(same_keywords) > 1:
            answer.append([movie, same_keywords])
    answer.sort(key= lambda x : len(x[1]), reverse=True)

    recommend_movies_by_overview = []
    for movie, keywords in answer:
        movie.genres = movie.genres.strip("[]").replace("'", "")
        recommend_movies_by_overview.append({'movie':movie, 'keywords':keywords})

    context = {
        'recommend_movies_by_overview' : recommend_movies_by_overview,
        'pick_movie' : pick_movie,
    }

    return render(request, 'movies/movie_for_you3.html', context)


def for_you4(request, movie_pk):
    pick_movie = get_object_or_404(Movie, pk=movie_pk)


    # 사운드 파일 추출 할거임 근데 토글을 마이크 버튼 필요할듯???
    import requests, json
    import queue, os, threading
    import sounddevice as sd
    import soundfile as sf
    from scipy.io.wavfile import write
    import time


    q = queue.Queue()
    recorder = False
    recording = False

    def complicated_record():
        with sf.SoundFile("sounds/temp.wav", mode='w', samplerate=16000, subtype='PCM_16', channels=1) as file:
            with sd.InputStream(samplerate=16000, dtype='int16', channels=1, callback=complicated_save):
                while recording:
                    file.write(q.get())
                        
    def complicated_save(indata, frames, time, status):
                q.put(indata.copy())
                
    def start():
                global recorder
                global recording
                recording = True
                recorder = threading.Thread(target=complicated_record)
                print('start recording')
                recorder.start()
                
    def stop():
                global recorder
                global recording
                recording = False

templates/movies/buy_list.html
{% extends 'base.html' %}



{% block content %}
<h1>장바구니</h1>


{% endblock content %}

templates/movies/movie_detail.html
{% extends 'base.html' %}

{% block content %}
<br><br><br><br>
<div class="detail-wrap container-fluid" style="padding-bottom: 150vh;">
  <!-- 정보 -->
  <div class="movie-info container-xxl mb-4">
    <!-- 제목 -->
    <div class="border-bottom p-3">
      <h1 class="text-light fw-bold mb-0">
        {{ movie.title }}
      </h1>
    </div>
    <!-- 장르 -->
    <div class="px-3 pt-2 mb-4">
      <div class="">
        <span class="text-secondary text-decoration-none fw-bold">
          {% for genre in genres %}{{ genre }}{% endfor %}
        </span>
      </div>
    </div>
    <!-- 줄거리, 버튼, 포스터 -->
    <div class="container-fluid d-flex justify-content-between mb-5">
      <div class="container-fluid ps-0 pe-5 me-5">
        <div class="mb-5">
          <span class="text-light fs-5">{{ movie.overview }}</span>
        </div>
        <div class="d-flex justify-content-between">
          <div>
            <button class="btn btn-danger me-2" style="width: 6rem;"><i class="fa-solid fa-star"></i> {{ movie.popularity }}</button>
            <button class="btn btn-secondary me-2" style="width: 6rem;"><a href="#create_review" style="text-decoration:none; color:white;">Review</a></button>
            <button class="btn btn-outline-light" style="width: 6rem;"><i class="fa-solid fa-basket-shopping"></i></button>
          </div>
          <a href="{% url 'movies:movies' %}" class="btn btn-dark" style="width: 6rem;">Back</a>
        </div>
      </div>
      <div class="d-flex justify-content-end">
        <img src="{{ movie.poster_path }}" alt="" style="height: 50vh; border-radius: 2%;">
      </div>
    </div>
    
    <h3 class="text-light fw-bold mb-3">Trailer</h3>
    <div class="row row-cols-4 mb-5">
      {% for video in video_list %}
      <div class="col mb-5" style="width: 36vw; height: 45vh;">
        <iframe  frameborder="0" height="100%" width="100%"
        src="{{ video.video }}" 
        allowfullscreen>
        </iframe>
      </div>
    {% endfor %}
    </div>
    

    <h3 class="text-light fw-bold mb-3">Screen shot</h3>
    <div class="row row-cols-4 mb-5">
      {% for img_movie in img_movies %}
      <div class="col mb-5" style="width: 16vw; height: 30vh;">
        <img src="{{ img_movie.img }}" alt="포스터 이미지" class="rounded" style="width: 100%; height: 100%; object-fit: cover;">
      </div>
      {% endfor %}
    </div>


    <h3 class="text-light fw-bold mb-3">Actors</h3>
    <div class="row row-cols-5 mb-5">
      {% for img_actor in img_actors %}
      <div class="col mb-2" style="width: 13vw; height: 25vh;">
        <img src="{{ img_actor.img }}" alt="포스터 이미지" class="rounded" style="width: 100%; height: 100%; object-fit: cover;">
        <h5 style="color:white; text-align:center;">{{img_actor.name}}</h5>
      </div>
      {% endfor %}
    </div>
  </div>

  <div class="container-xxl" style="background-color: #000;">
    <hr style="color:white">
    <div class="card" style="border: none;">
      <div class="card-body" style="background-color: #000;">
        <!-- 리뷰 목록 -->
        <a name="create_review">
        {% if movie.review_set.count > 0 %}
        <div class="container-fluid">
          {% for review in movie.review_set.all %}
          <div class="comment py-2">
            <!-- 작성자, 작성일, 수정일, 수정 버튼, 삭제 버튼 -->
            <div class="d-flex justify-content-between align-items-center">
              <div>
                <!-- 작성자 -->
                <a href="{% url 'accounts:profile' review.user.username %}" class="text-secondary text-decoration-none fw-bold">{{ review.user.username }}</a>
                <!-- 작성일 -->
                <span class="small text-secondary">
                  {{ review.created_at}}
                </span>
                <!-- 수정일 -->
                {% if review.updated_at %}
                <span class="small text-secondary">
                   | {{ review.updated_at}}
                </span>
                {% endif %}
              </div>
              <!-- 수정, 삭제 버튼 -->
              <div class="d-flex justify-content-end align-items-center">
                {% if request.user == review.user %}
                <a href="{% url 'movies:review_update' movie.pk review.pk %}" class="btn btn-sm  btn-outline-secondary me-2">Update</a>
                <!-- 삭제 -->
                <!-- Button trigger modal -->
                <button type="submit" class="btn btn-sm  btn-outline-secondary" data-bs-toggle="modal" data-bs-target="#commentDeleteButton">
                  Delete
                </button>
                <!-- Modal -->
                <div class="modal fade" id="commentDeleteButton" tabindex="-1" aria-labelledby="commentDeleteButtonLabel" aria-hidden="true">
                  <div class="modal-dialog">
                    <div class="modal-content bg-dark">
                      <div class="modal-header" style="border: none;">
                        <h5 class="modal-title text-light" id="commentDeleteButtonLabel">Delete</h5>
                        <button type="button" class="btn-close bg-secondary" data-bs-dismiss="modal" aria-label="Close"></button>
                      </div>
                      <div class="modal-body text-light">
                        Are you sure you want to delete it?
                      </div>
                      <div class="modal-footer" style="border: none;">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        <form action="{% url 'movies:review_delete' movie.pk review.pk %}" method="post">
                          {% csrf_token %}
                          <button type="submit" class="btn btn-danger">Delete</button>
                        </form>
                      </div>
                    </div>
                  </div>
                </div>
                {% comment %} <form action="{% url 'articles:comment_delete' article.pk comment.pk %}" method="post">
                  {% csrf_token %}
                  <button type="submit" class="btn btn-sm btn-dark text-secondary">Delete</button>
                </form> {% endcomment %}
                {% endif %}
              </div>
            </div>
            <!-- 평점 -->
            <div class="text-danger fw-bold small">
              {% if review.rating == 1 %}
              <i class="fa-solid fa-star"></i><i class="fa-regular fa-star"></i><i class="fa-regular fa-star"></i><i class="fa-regular fa-star"></i><i class="fa-regular fa-star"></i>
              {% elif review.rating == 2 %}
              <i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i><i class="fa-regular fa-star"></i><i class="fa-regular fa-star"></i><i class="fa-regular fa-star"></i>
              {% elif review.rating == 3 %}
              <i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i><i class="fa-regular fa-star"></i><i class="fa-regular fa-star"></i>
              {% elif review.rating == 4 %}
              <i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i><i class="fa-regular fa-star"></i>
              {% else %}
              <i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i>
              {% endif %}
            </div>
            <!-- 내용 -->
            <span class="text-light small">
              {{ review.content|linebreaksbr }}
            </span>
          </div>
          {% endfor %}
        </div>
        {% endif %}
      </div>
    </div>
  </div>
  <!-- 댓글 작성 -->
  <div class="container-xxl py-3" style="background-color: #000;">
    <div class="container-fluid">
      <form action="{% url 'movies:review_create' movie.pk %}" method="post" class="comment-create-form post-form my-3">
        {% csrf_token %}
        <textarea name="content" id="content" cols="5" rows="3" class="form-control my-3 bg-dark text-light" {% if not request.user.is_authenticated %}disabled{% endif %}>{{ review_form.content.value|default_if_none:'' }}</textarea>
        <select class="form-select bg-dark text-light mb-3" name="rating">
          <option value="1" selected>★☆☆☆☆</option>
          <option value="2">★★☆☆☆</option>
          <option value="3">★★★☆☆</option>
          <option value="4">★★★★☆</option>
          <option value="5">★★★★★</option>
        </select>
        <button type="submit" class="btn btn-danger fw-bold" style="width: 6rem;">Create</button>
      </form>
    </div>
  </div>
</div>


<a class="Follow" href="{% url 'movies:for_you' movie.pk %}"></a>


<style>
  .detail-wrap {
    background-image: linear-gradient(rgb(20, 20, 20), transparent, rgb(20, 20, 20)), url("{{ movie.poster_path }}");
    background-image: linear-gradient(rgba(0, 0, 0, 0.97), rgba(0, 0, 0, 0.90)), url("{{ movie.poster_path }}");
    background-repeat: no-repeat;
    background-size: cover;
    background-attachment: fixed;
  }

  .Follow { background:url("https://user-images.githubusercontent.com/89068148/169769128-9e6d8773-ff93-4e66-8da5-4b953a6a3a25.jpeg")no-repeat center / contain;
  width: 80px;
  height: 80px;
  bottom: 9px;
  right: 20px;
  display:block;
  position:fixed;
  border-radius:50%;
  z-index:999;
  animation:  rotation 10s infinite linear;
  }

  @-webkit-keyframes rotation {
    from {
        -webkit-transform: rotate(0deg);
    }
    to {
        -webkit-transform: rotate(359deg);
    }
  }
</style>
{% endblock %}

templates/movies/movies.html
{% extends 'base.html' %}

{% block content %}
<br><br><br><br>
<div class="container-fluid px-4">
  <h1 class="text-light">Movies</h1>
  <div class="row row-cols-2 row-cols-md-2 row-cols-lg-3 row-cols-xl-4 row-cols-xxl-5">

    {% for movie in movies %}
    <div class="my-5">
      <a href="{% url 'movies:movie_detail' movie.pk %}">
        <div class="movie-card">
          <img src="{{ movie.poster_path }}" alt="포스터 이미지" class="rounded">
          <div class="movie-info">
            <span class="text-danger text-center fs-2 fw-bold">{{ movie.title }}</span>
            <hr style="border-top: 2px solid #f8f9fa; width: 100%;">
            <span class="movie-overview d-inline-block text-secondary fw-light small">{{ movie.overview|truncatechars:150 }}</span>
          </div>
        </div>
      </a>
    </div>
    {% endfor %}



  <!-- 페이지네이션 -->
    <div class="container-fluid">
      <ul class="pagination pagination-lg justify-content-center py-5 pagination-custom">
        <!-- 맨처음 -->
        {% if 1 == movies.number %}
        <li class="page-item disabled">
          <a href="#" class="page-link" tabindex="-1" aria-disabled="true"><span aria-hidden="true">&laquo;</span></a>
        </li>
        {% else %}
        <li class="page-item">
          <a href="?page=1" class="page-link"><span aria-hidden="true">&laquo;</span></a>
        </li>
        {% endif %}
        <!-- 이전 페이지 -->
        {% if movies.has_previous %}
        <li class="page-item">
          <a href="?page={{ movies.previous_page_number }}" class="page-link">prev</a>
        </li>
        {% else %}
        <li class="page-item disabled">
          <a href="#" class="page-link" tabindex="-1" aria-disabled="true">prev</a>
        </li>
        {% endif %}
        <!-- 페이지 리스트 -->
        {% for page_number in movies.paginator.page_range %}
          {% if page_number >= movies.number|add:-3 and page_number <= movies.number|add:3 %}
            {% if page_number == movies.number %}
            <li class="page-item active" aria-current="page">
              <a href="?page={{ page_number }}" class="page-link">{{ page_number }}</a>
            </li>
            {% else %}
            <li class="page-item">
              <a href="?page={{ page_number }}" class="page-link">{{ page_number }}</a>
            </li>
            {% endif %}
          {% endif %}
        {% endfor %}
        <!-- 다음 페이지 -->
        {% if movies.has_next %}
        <li class="page-item">
          <a href="?page={{ movies.next_page_numger }}" class="page-link">next</a>
        </li>
        {% else %}
        <li class="page-item disabled">
          <a href="#" class="page-link" tabindex="-1" aria-disabled="true">next</a>
        </li>
        {% endif %}
        <!-- 마지막 -->
        {% if movies.paginator.num_pages != movies.number %}
        <li class="page-item">
          <a href="?page={{ movies.paginator.num_pages }}" class="page-link"><span aria-hidden="true">&raquo;</span></a>
        </li>
        {% else %}
        <li class="page-item disabled">
          <a href="#" class="page-link" tabindex="-1" aria-disabled="true"><span aria-hidden="true">&raquo;</span></a>
        </li>
        {% endif %}
      </ul>
    </div>
  </div>
</div>



<style>
  .movie-card {
    position: relative;
    overflow: hidden;
    width: 100%;
    height: 100%;
  }
  .movie-card img {
    width: 100%;
    height: 100%;
    transition: all 0.25s linear;
  }
  .movie-card:hover img {
    opacity: 0.07;
    transform: scale(1.25);
    border-radius: 0.375rem!important;
  }
  .movie-info {
    width: 80%;
    opacity: 0;
    transform: translateX(-50%) translateY(-50%);
    position: absolute;
    top: 80%;
    left: 50%;
    transition: all 600ms ease;
    display: flex;
    flex-direction: column;
    align-items: center;
  }
  .movie-card:hover .movie-info {
    opacity: 1;
    top: 50%;
  }

  .pagination-custom > li > a {
    background-color: #212529;
    color: #dc3545;
    border: 1px solid #212529;
  }
  .pagination-custom > li {
    --bs-pagination-hover-color: #212529!important;
    --bs-pagination-hover-bg: #dc3545!important;
    --bs-pagination-hover-border-color: #dc3545!important;
    --bs-pagination-focus-color: #212529!important;
    --bs-pagination-focus-bg: #dc3545!important;
    --bs-pagination-focus-box-shadow: 0 0 0 0.25rem rgba(220, 53, 69, 0.25)!important;
    --bs-pagination-active-color: #212529!important;
    --bs-pagination-active-bg: #dc3545!important;
    --bs-pagination-active-border-color: red!important;
    --bs-pagination-disabled-color: #000!important;
    --bs-pagination-disabled-bg: #212529!important;
    --bs-pagination-disabled-border-color: #212529!important;
  }

</style>
{% endblock %}