accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('profile/<username>', views.profile, name='profile'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),

    #kakao 
    path('kakao_login/', views.kakao_login, name='kakao_login'),
    path('kakao_unlink/', views.kakao_unlink, name='kakao_unlink'),
    path('auth/', views.oauth, name='auth'),
]

articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    # article
    path('', views.articles, name='articles'),
    path('create/', views.article_create, name='article_create'),
    path('<int:article_pk>/', views.article_detail, name='article_detail'),
    path('<int:article_pk>/update/', views.article_update, name='article_update'),
    path('<int:article_pk>/delete/', views.article_delete, name='article_delete'),
    path('<int:article_pk>/like/', views.article_like, name='article_like'),
    # comment
    path('<int:article_pk>/comments/create/', views.comment_create, name='comment_create'),
    path('<int:article_pk>/comments/<int:comment_pk>/update/', views.comment_update, name='comment_update'),
    path('<int:article_pk>/comments/<int:comment_pk>/delete/', views.comment_delete, name='comment_delete'),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
    path('search/', views.searching, name='search'),
]

movie_project/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', include('home.urls')),
    path('accounts/', include('accounts.urls')),
    path('articles/', include('articles.urls')),
    path('movies/', include('movies.urls')),

]

articles/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Article(models.Model): 
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_articles')
    
    def __str__(self):
        return self.title


class Comment(models.Model):  
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.title

articles/forms.py
from django import forms
from .models import Article, Comment


class ArticleForm(forms.ModelForm):
    
    class Meta:
        model = Article
        fields = ('title', 'content')



class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('content', )

articles/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_safe, require_http_methods, require_POST
from django.http import JsonResponse

from .forms import ArticleForm, CommentForm
from .models import Article, Comment


@require_safe
def articles(request):
    articles = Article.objects.order_by('-pk')
    context = {
        'articles': articles
    }
    return render(request, 'articles/articles.html', context)


@login_required
@require_http_methods(['GET', 'POST'])
def article_create(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST)
        if form.is_valid():
            article = form.save(commit=False)
            article.user = request.user
            article.save()
            return redirect('articles:article_detail', article.pk)
    else:
        form = ArticleForm()
    context = {
        'article_form': form
    }
    return render(request, 'articles/article_create.html', context)


@login_required
@require_safe
def article_detail(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    comment_set = article.comment_set.all()
    form = CommentForm()
    context = {
        'article': article,
        'comment_set': comment_set,
        'comment_form': form
    } 
    return render(request, 'articles/article_detail.html', context)



@login_required
@require_http_methods(['GET', 'POST'])
def article_update(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    if request.user != article.user:
        return redirect('articles:articles')
    if request.method == 'POST':
        form = ArticleForm(request.POST, instance=article)
        if form.is_valid():
            form.save()
            return redirect('articles:article_detail', article.pk)
    else:
        form = ArticleForm(instance=article)
    context = {
        'article': article,
        'article_form': form
    }
    return render(request, 'articles/article_update.html', context)



@require_POST
def article_delete(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    if request.user.is_authenticated:
        if request.user == article.user:
            article.delete()
            return redirect('articles:articles')
    return redirect('articles:article_detail', article.pk)



@require_POST
def article_like(request, article_pk):
    if request.user.is_authenticated:
        article = get_object_or_404(Article, pk=article_pk)
        if article.like_users.filter(pk=request.user.pk).exists():
            article.like_users.remove(request.user)
            liked = False
        else:
            article.like_users.add(request.user)
            liked = True
        context = {
            'liked': liked,
            'like_count': article.like_users.count(),
        }
        return JsonResponse(context)
    return redirect('accounts:login')



@require_POST
def comment_create(request, article_pk):
    if request.user.is_authenticated:
        article = get_object_or_404(Article, pk=article_pk)
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.article = article
            comment.user = request.user
            comment.save()
        return redirect('articles:article_detail', article.pk)
    return redirect('accounts:login')



# @require_POST
# def comment_update(request, article_pk, comment_pk):
#     article = get_object_or_404(Article, pk=article_pk)
#     comment = get_object_or_404(Comment, pk=comment_pk)
#     if request.user != comment.user:
#         return redirect('articles:article_detail', article_pk)
#     form = CommentForm(request.POST, instance=comment)
#     if form.is_valid():
#         form.save()
#         context = {
            
#         }
#         return JsonResponse(context)



@login_required
@require_http_methods(['GET', 'POST'])
def comment_update(request, article_pk, comment_pk):
    article = get_object_or_404(Article, pk=article_pk)
    comment = get_object_or_404(Comment, pk=comment_pk)
    if request.user != comment.user:
        return redirect('articles:article_detail', article_pk)
    if request.method == 'POST':
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            form.save()
            return redirect('articles:article_detail', article_pk)
    else:
        form = CommentForm(instance=comment)
    context = {
        'article': article,
        'comment': comment,
        'comment_form': form,
    }
    return render(request, 'articles/comment_update.html', context)



@require_POST
def comment_delete(request, article_pk, comment_pk):
    if request.user.is_authenticated:
        comment = get_object_or_404(Comment, pk=comment_pk)
        if request.user == comment.user:
            comment.delete()
    return redirect('articles:article_detail', article_pk)

templates/articles/article_create.html
{% extends 'base.html' %}

{% block content %}
<br><br><br><br>
<div class="container" style="height: 84vh;">
  <h2 class="my-3 border-bottom pb-2 text-secondary fw-bold">Article Create</h2>
  <form action="{% url 'articles:article_create' %}" method="post" class="post-form my-3">
    {% csrf_token %}
    <!-- 오류 표시 -->
    {% with form=article_form %}
      {% include 'errors.html' %}
    {% endwith %}
    <!-- 오류 표시 -->
    <div class="form-group my-3">
      <label for="title" class="form-label text-secondary">Title</label>
      <input type="text" name="title" id="title" class="form-control bg-secondary text-light">
    </div>
    <div class="form-group my-3">
      <label for="content" class="form-label text-secondary">Content</label>
      <textarea type="text" name="content" id="content" rows="10" class="form-control bg-secondary text-light"></textarea>
    </div>
    <button type="submit" class="btn btn-danger fw-bold">Create</button>
    <a href="{% url 'articles:articles' %}" class="btn btn-secondary fw-bold" style="width: 72.42px;">Back</a>
  </form>
</div>
{% endblock %}

templates/articles/article_detail.html
{% extends 'base.html' %}

{% block content %}
<br><br>
<div class="container-fluid" style="height: 81vh;">
  <div class="container my-5 bg-dark">
    <!-- 제목, 작성일 -->
    <div class="d-flex border-bottom p-3">
      <!-- 제목 -->
      <div class="col">
        <h2 class="text-light mb-0">
          {{ article.title }}
        </h2>
      </div>
      <!-- 작성일 -->
      <div class="col d-flex justify-content-end align-items-center">
        <span class="text-secondary small ms-auto">
          {{ article.created_at|date:'y-m-d H:i' }}
        </span>
      </div>
    </div>
    <!-- 작성자, 수정일 -->
    <div class="row px-3 py-2">
      <!-- 작성자 -->
      <div class="col">
        <a href="{% url 'accounts:profile' article.user.username %}" class="text-secondary text-decoration-none fw-bold">{{ article.user.username }}</a>
      </div>
      <!-- 수정일 -->
      <div class="col d-flex justify-content-end align-items-center">
        {% if article.updated_at %}
        <span class="text-secondary small ms-auto">
          {{ article.updated_at|date:'y-m-d H:i' }}
        </span>
        {% endif %}
      </div>
    </div>
    <!-- 게시글 row -->
    <div class="row my-3">
      <div class="card bg-dark" style="border: none;">
        <!-- 내용 -->
        <div class="card-body bg-dark">
          <div class="card-text mb-2 text-light">
            {{ article.content|linebreaks }}
          </div>
        </div>
        <div class="container d-flex justify-content-between align-items-center px-0">
          <!-- 수정, 삭제 버튼 -->
          {% if request.user == article.user %}
          <div class="d-flex justify-content-start my-3">
            <div class="me-2">
              <a href="{% url 'articles:article_update' article.pk %}" class="btn btn-dark btn-outline-secondary p-2 fw-bold">
                Update
              </a>
            </div>
            <!-- Button trigger modal -->
            <button type="submit" class="btn btn-outline-secondary p-2 fw-bold" data-bs-toggle="modal" data-bs-target="#articleDeleteButton">
              Delete
            </button>
            <!-- Modal -->
            <div class="modal fade" id="articleDeleteButton" tabindex="-1" aria-labelledby="articleDeleteButtonLabel" aria-hidden="true">
              <div class="modal-dialog">
                <div class="modal-content bg-dark">
                  <div class="modal-header" style="border: none;">
                    <h5 class="modal-title text-light" id="articleDeleteButtonLabel">Delete</h5>
                    <button type="button" class="btn-close bg-secondary" data-bs-dismiss="modal" aria-label="Close"></button>
                  </div>
                  <div class="modal-body text-light">
                    Are you sure you want to delete it?
                  </div>
                  <div class="modal-footer" style="border: none;">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <form action="{% url 'articles:article_delete' article.pk %}" method="post">
                      {% csrf_token %}
                      <button type="submit" class="btn btn-danger">Delete</button>
                    </form>
                  </div>
                </div>
              </div>
            </div>
            {% comment %} <form action="{% url 'articles:article_delete' article.pk %}" method="post">
              {% csrf_token %}
              <button type="submit" class="btn btn-secondary p-2 fw-bold">
                Delete
              </button>
            </form> {% endcomment %}
          </div>
          {% endif %}
          <!-- 목록으로 -->
          <div class="my-3">
            <a href="{% url 'articles:articles' %}" class="btn btn-sm btn-dark btn-outline-secondary p-2 px-3 text-secondary fw-bold">Back</a>
          </div>
        </div>
      </div>
    </div>
  
  
    <!-- 좋아요 버튼, 좋아요 수, 댓글 수 -->
    <div class="d-flex border-bottom my-2">
      <!-- 좋아요 버튼 -->
      {% if request.user.is_authenticated %}
      <form class="like-form p-0" data-article-id="{{ article.pk }}">
        {% csrf_token %}
        {% if user in article.like_users.all %}
        <button id="like-{{ article.pk }}" class="btn btn-link text-danger text-decoration-none fs-4"><i class="fa fa-solid fa-heart text-danger"></i></button>
        {% else %}
        <button id="like-{{ article.pk }}" class="btn btn-link text-secondary text-decoration-none fs-4"><i class="fa fa-regular fa-heart text-secondary"></i></button>
        {% endif %}
      </form>
      {% endif %}
      <!-- 좋아요 수 -->
      <div class="d-flex align-items-center justify-content-center p-0 m-0 me-3">
        <span class="text-secondary">
          좋아요
        </span>
        <span id="like-count-{{ article.pk }}" class="ms-2 text-light fw-bold">
          {{ article.like_users.all|length }}
        </span>
      </div>
      <!-- 댓글 아이콘 -->
      <div class="d-flex justify-content-center align-items-center me-2">
        <i class="fa fa-regular fa-comment text-secondary"></i>
      </div>
      <!-- 댓글 수 -->
      <div class="d-flex align-items-center justify-content-center p-0 m-0">
        <span class="text-secondary">
          댓글
        </span>
        <span class="ms-2 text-light fw-bold">
          {{ article.comment_set.all.count }}
        </span>
      </div>
    </div>
  
  
    <div class="card bg-dark" style="border: none;">
      <div class="card-body bg-dark">
        <!-- 댓글 목록 -->
        {% if article.comment_set.count > 0 %}
        <div class="container-fluid">
          {% for comment in article.comment_set.all %}
          <div class="comment py-2">
            <!-- 작성자, 작성일, 수정일, 수정 버튼, 삭제 버튼 -->
            <div class="d-flex justify-content-between align-items-center">
              <div>
                <!-- 작성자 -->
                <a href="{% url 'accounts:profile' comment.user.username %}" class="text-secondary text-decoration-none fw-bold">{{ comment.user.username }}</a>
                <!-- 작성일 -->
                <span class="small text-secondary">
                  {{ comment.created_at|date:'y-m-d H:i' }}
                </span>
                <!-- 수정일 -->
                {% if comment.updated_at %}
                <span class="small text-secondary">
                   | {{ comment.updated_at|date:'y-m-d H:i' }}
                </span>
                {% endif %}
              </div>
              <!-- 수정, 삭제 버튼 -->
              <div class="d-flex justify-content-end align-items-center">
                {% if request.user == comment.user %}
                {% comment %} <form action="{% url 'articles:comment_update' article.pk comment.pk %}" method="post">
                  {% csrf_token %}
                  <button type="submit" class="text-info">Update</button>
                </form> {% endcomment %}
                <!-- 수정 -->
                {% comment %} <form action="#" method="get" class="me-2">
                  {% csrf_token %}
                  <button type="submit" class="btn btn-sm btn-secondary">Update</button>
                </form> {% endcomment %}
                <a href="{% url 'articles:comment_update' article.pk comment.pk %}" class="btn btn-sm  btn-outline-secondary me-2">Update</a>
                <!-- 삭제 -->
                <!-- Button trigger modal -->
                <button type="submit" class="btn btn-sm  btn-outline-secondary" data-bs-toggle="modal" data-bs-target="#commentDeleteButton">
                  Delete
                </button>
                <!-- Modal -->
                <div class="modal fade" id="commentDeleteButton" tabindex="-1" aria-labelledby="commentDeleteButtonLabel" aria-hidden="true">
                  <div class="modal-dialog">
                    <div class="modal-content bg-dark">
                      <div class="modal-header" style="border: none;">
                        <h5 class="modal-title text-light" id="commentDeleteButtonLabel">Delete</h5>
                        <button type="button" class="btn-close bg-secondary" data-bs-dismiss="modal" aria-label="Close"></button>
                      </div>
                      <div class="modal-body text-light">
                        Are you sure you want to delete it?
                      </div>
                      <div class="modal-footer" style="border: none;">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        <form action="{% url 'articles:comment_delete' article.pk comment.pk %}" method="post">
                          {% csrf_token %}
                          <button type="submit" class="btn btn-danger">Delete</button>
                        </form>
                      </div>
                    </div>
                  </div>
                </div>
                {% comment %} <form action="{% url 'articles:comment_delete' article.pk comment.pk %}" method="post">
                  {% csrf_token %}
                  <button type="submit" class="btn btn-sm btn-dark text-secondary">Delete</button>
                </form> {% endcomment %}
                {% endif %}
              </div>
            </div>
            <!-- 내용 -->
            <span class="text-light small">
              {{ comment.content|linebreaksbr }}
            </span>
          </div>
          {% endfor %}
        </div>
        {% endif %}
        <!-- 댓글 작성 -->
        <div class="container my-3">
          <form action="{% url 'articles:comment_create' article.pk %}" method="post" class="comment-create-form post-form my-3" data-article-id="{{ article.pk }}">
            {% csrf_token %}
            <textarea name="content" id="content" cols="5" rows="3" class="form-control my-3 bg-dark text-light" {% if not request.user.is_authenticated %}disabled{% endif %}>{{ comment_form.content.value|default_if_none:'' }}</textarea>
            <button type="submit" class="btn btn-danger fw-bold">Create</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}



{% block script %}
<script>
const likeForm = document.querySelector('.like-form');
likeForm.addEventListener('submit', event => {
  event.preventDefault();
  const articleId = event.target.dataset.articleId;
  const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;
  axios({
    url: `/articles/${articleId}/like/`,
    method: 'post',
    headers: { 'X-CSRFToken': csrftoken },
  })
    .then(res => {
      const likeCount = res.data.like_count;
      const liked = res.data.liked;
      const $likeButton = document.querySelector(`#like-${articleId}`);
      const $likeCount = document.querySelector(`#like-count-${articleId}`);
      if (liked) {
        $likeButton.classList.add('text-danger');
        $likeButton.innerHTML ='<i class="fa fa-solid fa-heart text-danger"></i>';
      } else {
        $likeButton.classList.remove('text-danger');
        $likeButton.innerHTML = '<i class="fa fa-regular fa-heart text-secondary"></i>';
      }
      $likeCount.innerText = likeCount;
    })
    .catch(err => console.error(err.response));
});


{% comment %} const $commentCreateForm = document.querySelector('.comment-create-form');
$commentCreateForm.addEventListener('submit', event =>{
  event.preventDefault();
  const articleId = event.target.dataset.articleId;
  const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;
  axios({
    url: `/articles/${articleId}/comments/create/`,
    method: 'post',
    headers: { 'X-CSRFToken': csrftoken },
  })
    .then(res => {
      console.log(res.data);
    })
    .catch(err => console.error(err.response));
}); {% endcomment %}
</script>
{% endblock %}

templates/articles/article_update.html
{% extends 'base.html' %}

{% block content %}
<br><br><br><br><br><br>
<div class="container" style="height: 84vh;">
  <h2 class="my-3 border-bottom pb-2 text-secondary fw-bold">Article Update</h2>
  <form method="post" class="post-form my-3">
    {% csrf_token %}
    <!-- 오류 표시 -->
    {% with form=article_form %}
      {% include 'errors.html' %}
    {% endwith %}
    <!-- 오류 표시 -->
    <div class="form-group my-3">
      <label for="title" class="form-label text-secondary">Title</label>
      <input type="text" name="title" id="title" value="{{ article_form.title.value|default_if_none:'' }}" class="form-control bg-secondary text-light">
    </div>
    <div class="form-group my-3">
      <label for="content" class="form-label text-secondary">Content</label>
      <textarea type="text" name="content" id="content" rows="10" class="form-control bg-secondary text-light">{{ article_form.content.value|default_if_none:'' }}</textarea>
    </div>
    <button type="submit" class="btn btn-danger fw-bold">Update</button>
    <a href="{% url 'articles:articles' %}" class="btn btn-secondary fw-bold" style="width: 78.75px;">Back</a>
  </form>
</div>
{% endblock %}

templates/articles/articles.html
{% extends 'base.html' %}

{% block content %}
<br><br><br><br>
<div class="container-fluid px-4" style="height: 86vh;">
  <h1 class="text-light">Community</h1>
  <div class="container bg-dark p-2 my-5">
    <table class="table table-hover bg-dark rounded">
      <!-- thead -->
      <thead>
        <tr class="text-center text-secondary">
          <th scope="col" class="col-1">번호</th>
          <th scope="col" class="col-1"><i class="fa fa-solid fa-heart text-danger"></i></th>
          <th scope="col" class="col-5">제목</th>
          <th scope="col" class="col-3">작성자</th>
          <th scope="col" class="col-2">작성일</th>
        </tr>
      </thead>
      <!-- tbody -->
      <tbody>
        {% for article in articles %}
        <tr class="text-center text-light">
          <!-- 게시글 번호 -->
          <td class="text-end text-secondary">
            {{ article.pk }}
          </td>
          <!-- 좋아요 수 -->
          <td>
            {% if article.like_users.count > 0 %}
              <span class="badge text-bg-danger fw-bold">
                {{ article.like_users.count }}
              </span>
            {% endif %}
          </td>
          <!-- 제목, 댓글 수 -->
          <td class="text-start">
            <a href="{% url 'articles:article_detail' article.pk %}" class="text-decoration-none">
              <span class="text-light">{{ article.title }}</span>
              {% if article.comment_set.count > 0 %}
                <span class="small text-danger fw-bold py-2">
                  {{ article.comment_set.count }}
                </span>
              {% endif %}
            </a>
          </td>
          <!-- 작성자 -->
          <td>
            <a href="{% url 'accounts:profile' article.user.username %}" class="text-decoration-none">
              <span class="text-light">{{ article.user.username }}</span>
            </a>
          </td>
          <!-- 작성일 -->
          <td>
            <span class="text-secondary" style="font-size: 12px;">{{ article.created_at|date:'y-m-d H:i' }}</span>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    <!-- 작성 버튼 -->
    <div class="container d-flex justify-content-end">
      <a href="{% url 'articles:article_create' %}" class="btn btn-danger fw-bold fs-5 px-3 text-spacing">Create</a>
    </div>
  </div>
</div>
{% endblock %}


{% block script %}
<script>
  
</script>
{% endblock %}

templates/articles/comment_update.html
{% extends 'base.html' %}

{% block content %}
<br><br><br><br>
<div class="container">
  <h2 class="my-3 border-bottom pb-2 text-secondary fw-bold">Comment Update</h2>
  <form method="post" class="post-form my-3">
    {% csrf_token %}
    <!-- 오류 표시 -->
    <!-- 오류 표시 -->
    <div class="form-group my-3">
      <label for="content" class="form-label text-secondary">Content</label>
      <textarea type="text" name="content" id="content" rows="10" class="form-control bg-secondary text-light">{{ comment_form.content.value|default_if_none:'' }}</textarea>
    </div>
    <button type="submit" class="btn btn-danger fw-bold">Update</button>
    <a href="{% url 'articles:article_detail' article.pk %}" class="btn btn-secondary fw-bold" style="width: 78.75px;">Back</a>
  </form>
</div>
{% endblock %}