accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('profile/<username>', views.profile, name='profile'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),

    #kakao 
    path('kakao_login/', views.kakao_login, name='kakao_login'),
    path('kakao_unlink/', views.kakao_unlink, name='kakao_unlink'),
    path('auth/', views.oauth, name='auth'),
]

articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    # article
    path('', views.articles, name='articles'),
    path('create/', views.article_create, name='article_create'),
    path('<int:article_pk>/', views.article_detail, name='article_detail'),
    path('<int:article_pk>/update/', views.article_update, name='article_update'),
    path('<int:article_pk>/delete/', views.article_delete, name='article_delete'),
    path('<int:article_pk>/like/', views.article_like, name='article_like'),
    # comment
    path('<int:article_pk>/comments/create/', views.comment_create, name='comment_create'),
    path('<int:article_pk>/comments/<int:comment_pk>/update/', views.comment_update, name='comment_update'),
    path('<int:article_pk>/comments/<int:comment_pk>/delete/', views.comment_delete, name='comment_delete'),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
    path('search/', views.searching, name='search'),
]

movie_project/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', include('home.urls')),
    path('accounts/', include('accounts.urls')),
    path('articles/', include('articles.urls')),
    path('movies/', include('movies.urls')),

]

movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    # movie
    path('', views.movies, name='movies'),
    path('<int:movie_pk>/', views.movie_detail, name='movie_detail'),
    # review
    path('<int:movie_pk>/reviews/create', views.review_create, name='review_create'),
    path('<int:movie_pk>/reviews/<int:review_pk>/update/', views.review_update, name='review_update'),
    path('<int:movie_pk>/reviews/<int:review_pk>/delete/', views.review_delete, name='review_delete'),
    
    # 영화 추천
    path('for-you/<int:movie_pk>/', views.for_you, name='for_you'),
    path('for-you2/<int:movie_pk>/', views.for_you2, name='for_you2'),
    path('for-you3/<int:movie_pk>/', views.for_you3, name='for_you3'),
    path('for-you4/<int:movie_pk>/', views.for_you4, name='for_you4'),
]

templates/_footer.html
<div class="container-fluid" id="footer">
  <footer class="d-flex flex-wrap justify-content-between align-items-center py-2">
    <div class="col-md-4 d-flex align-items-center">
      <div class="container-fluid">
        <div class="mb-3 mb-md-0 text-secondary">SSAFY 7기 구미 3반 10조 임진현, 함희주</div>
      </div>
    </div>

    <ul class="nav col-md-4 justify-content-end list-unstyled d-flex icons">
      <li class="ms-3"><a class="text-secondary" href="https://www.instagram.com/"><i class="fa-brands fa-instagram fa-2x"></i></a></li>
      <li class="ms-3"><a class="text-secondary" href="https://ko-kr.facebook.com/"><i class="fa-brands fa-facebook fa-2x"></i></a></li>
      <li class="ms-3"><a class="text-secondary" href="https://twitter.com/?lang=ko"><i class="fa-brands fa-twitter fa-2x"></i></a></li>
    </ul>
  </footer>
</div>

<style>
#footer {
  width: 100%;
  height: 60px;
  bottom: 0px;
  position: absolute;
}
footer {
  border-top: 1px solid #6c757d!important;
}
.icons > li > a:hover {
  color: #f8f9fa!important;
  transition: all linear 0.2s;
}
</style>

templates/_navbar.html
<nav class="navbar fixed-top navbar-expand-md navbar-dark bg-black">
  <div class="container-fluid">
    
    <a href="{% url 'home:home' %}" class="navbar-brand nav-link text-danger fw-bold fs-4 me-5" style="font-family: 'Anton', sans-serif;">D - FLEX</a>


    <div class="navbar-nav me-auto mb-2 mb-lg-0">
      <div class="row justify-content-between">
        <div class="col d-flex justify-content-center">
          <a href="{% url 'articles:articles' %}" class="link-secondary text-decoration-none fs-5 fw-bold">Community</a>
        </div>
        <div class="col d-flex justify-content-center">
          <a href="{% url 'movies:movies' %}" class="link-secondary text-decoration-none fs-5 fw-bold">Movies</a>
        </div>
      </div>
    </div>


    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        {% if user.is_authenticated %}
          <!-- Profile -->
          <li class="nav-item">
            <a href="{% url 'accounts:profile' user.username %}" class="nav-link"> <i class="fa-solid fa-user fa-lg" style="color:gray;"></i> {{ user.username }}</a>
          </li>
          <!-- Logout -->
          <li class="nav-item">
            <!-- Button trigger modal -->
            <button type="submit" class="btn btn-dark nav-link" style="border: 2px;" data-bs-toggle="modal" data-bs-target="#exampleModal">
              Logout
            </button>
            <style>
              .btn-dark {
                --bs-btn-bg: none;
                --bs-btn-hover-bg: none;
              }
            </style>
            <!-- Modal -->

            {% comment %} <form action="{% url 'accounts:logout' %}" method="post">
              {% csrf_token %}
              <button type="submit" class="bg-dark-secondary nav-link" style="border: none;">Logout</button>
            </form> {% endcomment %}
          </li>
        {% else %}
          <!-- Login -->
          <li class="nav-item">
            <a href="{% url 'accounts:login' %}" class="nav-link">Login</a>
          </li>
          <!-- Signup -->
          <li class="nav-item">
            <a href="{% url 'accounts:signup' %}" class="nav-link">Signup</a>
          </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

templates/base.html
<!DOCTYPE html>

{% load static %}

<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <!-- CSS only -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'style.css' %}">
  <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  <script src="https://kit.fontawesome.com/120edf5eb4.js" crossorigin="anonymous"></script>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Anton&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  
  <title>D-FLEX</title>
</head>
<body class="bg-black">
  
  <div id="wrap">
    {% include '_navbar.html' %}

    <section>
      {% block content %}
      {% endblock %}
    </section>

    {% include '_footer.html' %}
  </div>

  {% block script %}
  {% endblock %}
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
  <!-- Modal -->
  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content bg-dark">
        <div class="modal-header" style="border: none;">
          <h5 class="modal-title text-light" id="exampleModalLabel">Logout</h5>
          <button type="button" class="btn-close bg-secondary" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body text-light">
          Are you sure you want to log out?
        </div>
        <div class="modal-footer" style="border: none;">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <form action="{% url 'accounts:logout' %}" method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Logout</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</body>
</html>

<style>
#wrap {
  min-height: 100vh;
  position: relative;
  width: 100%;
}
section {
  padding-bottom: 90px;
}
</style>

templates/errors.html
{% if form.errors %}
<div class="alert alert-danger">
  {% for field in form %}
    {% if field.errors %}
    <div>
      <strong>{{ field.label }}</strong>
      {% for error in field.errors %}
        <li class="list-group-item">{{ error }}</li>
      {% endfor %}
    </div>
    {% endif %}
  {% endfor %}

  {% for error in form.non_field_errors %}
  <div>
    <strong>{{ error }}</strong>
  </div>
  {% endfor %}
</div>
{% endif %}